# Generated by Django 4.0.5 on 2022-06-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0175_delete_usermodel'),
        ('Errorreports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetailsNotEntered',
            fields=[
            ],
            options={
                'verbose_name': 'Bank Detail Not Entered',
                'verbose_name_plural': 'Bank Details Not Entered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
        migrations.CreateModel(
            name='PanDetailsNotEntered',
            fields=[
            ],
            options={
                'verbose_name': 'PAN Detail Not Entered',
                'verbose_name_plural': 'PAN Details Not Entered',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('TUFIDCOapp.mastersanctionform',),
        ),
    ]
