# Generated by Django 4.0.5 on 2022-06-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUFIDCOapp', '0174_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userModel',
        ),
    ]
